### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by boxingYi** [tdhungit/HanaPlatform#1]
![image](https://user-images.githubusercontent.com/773656/38202957-2bd71d12-36d0-11e8-8ecd-13d0ea60063b.png)

Hi , @tdhungit , I clone this project and run : meteor npm install   && meteor . There seems to be a problem when access: http://localhost:3000.

**Comment by tdhungit** [comment]
Hi @boxingYi,

I use redux dev tool to debug redux so please setup redux dev tool: https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd

If you no need debug redux please access file: imports/ui/default/store/index.js 
and comment: window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()

I updated how to install.

thanks your feedback

**Comment by boxingYi** [comment]
Hi, @tdhungit 
Great，it work !   thanks ~
![image](https://user-images.githubusercontent.com/773656/38240548-73a8989a-3762-11e8-8686-ce481a2021da.png)
